### ISSUE TITLE
Fails to compile with SDK 2.2.0

### ISSUE THREAD

**Issue by fhoedemakers** [fhoedemakers/pico-infonesPlus#129]
See also https://github.com/Wren6991/PicoDVI/issues/91

[68%] Building ASM object CMakeFiles/piconesPlus.dir/pico_lib/dvi/tmds_encode.S.o
/home/pi/pico-sdk2.2.0-tusb-latest/src/boards/include/boards/pico2.h: Assembler messages:
/home/pi/pico-sdk2.2.0-tusb-latest/src/boards/include/boards/pico2.h:17: Error: bad instruction `pico_board_cmake_set(PICO_PLATFORM, rp2350)'
/home/pi/pico-sdk2.2.0-tusb-latest/src/boards/include/boards/pico2.h:78: Error: bad instruction `pico_board_cmake_set_default(PICO_FLASH_SIZE_BYTES, (4*1024*1024))'
/home/pi/pico-sdk2.2.0-tusb-latest/src/boards/include/boards/pico2.h:96: Error: bad instruction `pico_board_cmake_set_default(PICO_RP2350_A2_SUPPORTED, 1)'
make[2]: *** [CMakeFiles/piconesPlus.dir/build.make:1073: CMakeFiles/piconesPlus.dir/pico_lib/dvi/tmds_encode.S.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by fhoedemakers** [comment]
Solved by adding #include "pico.h" in pico_lib/dvi/tmds_encode.S
